# Copyright NDS Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ORG.DOMAIN:
  peer0.ORG.DOMAIN:
  peer1.ORG.DOMAIN:

networks:
  default:

services:

  ca.ORG.DOMAIN:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    restart: always
    environment:
      # CA Server Setting
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ORG
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ORG.DOMAIN-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ORG.DOMAIN-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
      # CA Client Setting
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client
      - FABRIC_CA_CLIENT_CA_NAME=ca-ORG
      - FABRIC_CA_CLIENT_TLS_ENABLED=true
      - FABRIC_CA_CLIENT_TLS_CERTFILE=/etc/hyperledger/fabric-ca-client-config/ca.ORG.DOMAIN-cert.pem
      - FABRIC_CA_CLIENT_TLS_KEYFILE=/etc/hyperledger/fabric-ca-client-config/CA_PRIVATE_KEY
      - FABRIC_CA_CLIENT_CA_CERTFILE=/etc/hyperledger/fabric-ca-client-config/ca.ORG.DOMAIN-cert.pem
      - TZ=Asia/Seoul
    ports:
      - "CA_PORT:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile $FABRIC_CA_SERVER_CA_CERTFILE --ca.keyfile $FABRIC_CA_SERVER_CA_KEYFILE -b admin:adminpw -d'
    volumes:
      - ./../artifacts/crypto-config/peerOrganizations/ORG.DOMAIN/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./../artifacts/crypto-config/peerOrganizations/ORG.DOMAIN/ca/:/etc/hyperledger/fabric-ca-client-config
      - ./../artifacts/fabric-ca-server-config.yaml/:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      # - ./../artifacts/fabric-ca-client-config.yaml/:/etc/hyperledger/fabric-ca-client/fabric-ca-client-config.yaml
    container_name: ca.ORG.DOMAIN
    networks:
      - default

  orderer.ORG.DOMAIN:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ORG.DOMAIN
    container_name: orderer.ORG.DOMAIN
    networks:
      - default

  peer0.ORG.DOMAIN:
    container_name: peer0.ORG.DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ORG.DOMAIN
    networks:
      - default

  peer1.ORG.DOMAIN:
    container_name: peer1.ORG.DOMAIN
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ORG.DOMAIN
    networks:
      - default
